### ISSUE TITLE
Error when installing with conda 

### ISSUE THREAD

**Issue by aazocar** [pyscal/pyscal_rdf#64]
When creating an l12 structure, it gives the following error:

> TypeError: System.init() got an unexpected keyword argument 'species'

The versions of pyscal and pyscal_rdf in conda are:

pyscal-rdf                0.1.5
pyscal3                   3.1.1

**Comment by srmnitc** [comment]
Thanks for reporting. This is due to the old version of pyscal3. Now the conda recipe is being updated which will fix the issue.

**Comment by srmnitc** [comment]
fixed in v0.1.7
